### ISSUE TITLE
Update to 1.*.* OTEL SDK

### ISSUE THREAD

**Issue by arizanovj** [spiral/otel-bridge#7]
New non `0.0.X` version (https://github.com/opentelemetry-php/sdk/releases/tag/1.0.0) has been released for the `OTEL SDK`. Is there any plan for updating to it ? 
Not sure what the implications are on the current code in the `otel-bridge`, it might be changing of few namaspaces or it might need more work ?

**Comment by Lisio** [comment]
Is this package dead? Unusable with opentelemetry 1.0.1.
